"""
SYN - Markdown Raporlama Modülü
"""

from datetime import datetime
from typing import List, Dict, Any
import numpy as np


class MarkdownReporter:
    """Tarama sonuçlarını Github/Gitlab uyumlu Markdown formatında raporlar."""

    def generate(self, results: List[Dict[str, Any]], cve_engine, filename: str = "syn_report.md"):
        lines = []
        lines.append("# SYN Penetration Test Report\n")
        lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

        # Summary
        open_count = sum(1 for r in results if r.get('status') in ['OPEN', 'OPEN | FILTERED'])
        targets = set(r.get('target_ip', '?') for r in results if r.get('status') in ['OPEN', 'OPEN | FILTERED'])
        lines.append("## Summary\n")
        lines.append(f"- **Targets Scanned:** {len(targets)}")
        lines.append(f"- **Open Ports Found:** {open_count}\n")

        # Results table
        lines.append("## Scan Results\n")
        lines.append("| Target IP | Port | State | Service/Banner | AI OS | Risk Level | Details |")
        lines.append("|---|---|---|---|---|---|---|")

        for res in results:
            if res.get('status') not in ['OPEN', 'OPEN | FILTERED']:
                continue

            ip = res.get('target_ip', '127.0.0.1')
            port = res.get('port', 'N/A')
            state = res.get('status', 'Unknown')

            banner = str(res.get('banner', '-') or '-').replace('\n', ' ').replace('\r', '').replace('|', '/')
            if len(banner) > 50:
                banner = banner[:47] + "..."

            os_guess = res.get('ai_os_tahmini', 'Unknown')
            if isinstance(os_guess, (list, np.ndarray)):
                os_guess = str(os_guess[0])

            risk_analysis = cve_engine.evaluate_result(res)
            decision = risk_analysis['decision']

            if decision == 'CRITICAL RISK':
                decision_str = "🔴 **CRITICAL**"
            elif decision == 'HIGH RISK':
                decision_str = "🟠 **HIGH**"
            elif decision == 'MEDIUM RISK':
                decision_str = "🟡 **MEDIUM**"
            elif decision == 'LOW RISK':
                decision_str = "🟢 LOW"
            else:
                decision_str = "✅ SAFE"

            if decision != 'NO_ACTION':
                warning = risk_analysis.get('Warning', '').replace('\n', ' ').replace('|', '/')
                action = risk_analysis.get('Action', '').replace('\n', ' ').replace('|', '/')
                details = f"{warning} → {action}"
            else:
                details = "-"

            lines.append(f"| {ip} | {port} | {state} | `{banner}` | {os_guess} | {decision_str} | {details} |")

        lines.append("\n---")
        lines.append("*Generated by SYN AI-Powered Pentest Framework*\n")

        content = "\n".join(lines)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)

        return filename
